Get method
JesusPaz/workshop-api-testing-js pull request #7
Opened 2019-09-04 21:03 UTC by JesusPaz

Add method to download the repo and check that the file exists.

2019-09-04 21:14 UTC, holgiosalos requested changes

2019-09-04 21:14 UTC, holgiosalos commented on test/GithubApi.Repositories.test.js
> +      expect(found.name).to.equal('jasmine-awesome-report');
agrega un assert para verificar primero que `found` no es empty ni undefined, si por algun motivo el repo no existiera, ese assert evitaria que los siguientes que tienes fallen porque found no tenga las propiedades name, private o description.

2019-09-04 21:16 UTC, holgiosalos requested changes

2019-09-04 21:16 UTC, holgiosalos commented on .vscode/launch.json
> +    // Use IntelliSense to learn about possible attributes.
elimina estos comentarios del archivo

2019-09-04 21:57 UTC, holgiosalos commented
Aumenta el tiempo de timeout para evitar fallos en travis. Normalmente, cuando un check pasa pero el otro no, puede ser ocasionado por problemas de timeout. Sino, puede ser porque sólo debe haber una global.secure en el archivo de configuracion de travis. Como utilizaste la version .com de travis, sigue estos pasos:
- borra las lineas 12 y 13 del .travis.yml
- vuelve a ejecutar los siguientes comandos:
```
travis login --pro
travis encrypt ACCESS_TOKEN="your-access-token" --add --com
```
- haz commit y luego push 

Si despues de todo esto, sigue teniendo fallos ocasionales de la api de github, puede ser que te esten bloqueando temporalmente ya que hay un limite de request por minuto.

2019-09-06 00:39 UTC, holgiosalos approved these changes

2019-09-06 00:39 UTC, holgiosalos commented on test/GithubApi.Repositories.test.js
> +        .set('User-Agent', 'agent');
agrega el `.auth('token', process.env.ACCESS_TOKEN)` para evitar que te fallen los tests por permisos.

2019-09-06 00:42 UTC, holgiosalos requested changes

2019-09-06 00:42 UTC, holgiosalos commented on test/GithubApi.Repositories.test.js
> +      const responseUsers = await agent.get(`${urlBase}/users/${githubUserName}`)
`.auth('token', process.env.ACCESS_TOKEN)`

2019-09-06 00:50 UTC, JesusPaz commented on test/GithubApi.Repositories.test.js
> +        .set('User-Agent', 'agent');
Si funciona?, creo que el token es para acceder a mis repositorios.

Como se esta haciendo el get a "https://api.github.com/users/aperdomob", no deberia dar un error por que es su repositorio?

2019-09-06 00:59 UTC, holgiosalos commented on test/GithubApi.Repositories.test.js
> +        .set('User-Agent', 'agent');
Tienes razon, solo que como en principio fallaron los build por un forbidden, pense que nos faltaba el token. Pero ya estan los dos en verde, osea que todo bien. puedes hacer merge

2019-09-06 01:00 UTC, holgiosalos approved these changes

2019-09-06 11:25 UTC, merged